version: "3"
name: "crud-react-postgres-node"
services:
  db:
    container_name: postgres
    env_file:
      - .env
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - ${POSTGRES_HOST}
      - ${POSTGRES_PASSWORD}
      - ${POSTGRES_USER}
      - ${POSTGRES_PORT}
      - ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cruddb"]
      interval: 60s
      timeout: 20s
      retries: 5
    volumes:
      - db:/data/postgres

  app:
    container_name: node-app
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - ${SERVER_PORT}
      - ${POSTGRES_HOST}
      - ${POSTGRES_PASSWORD}
      - ${POSTGRES_USER}
      - ${POSTGRES_PORT}
      - ${POSTGRES_DB}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started

volumes:
  db:
